Controllers/ContactController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AdminLTE_MVC.Controllers
{
    //[Authorize]
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/FormsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AdminLTE_MVC.Controllers
{
    //[Authorize]
    public class FormsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TestPage()
        {
            return View();
        }
    }
}

Views/Shared/AdminLTE/_Footer.cshtml
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline">
    Anything you want
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

Views/Shared/AdminLTE/_MainNavigation.cshtml
@using AdminLTE_MVC.Helpers;

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a asp-area="" asp-controller="Home" asp-action="Index" class="brand-link">
    <img src="~/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">AdminLTE 3</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">

    <!-- Search Form -->
    <div class="form-inline mt-2">
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

        <!-- Home -->
        <li class="nav-item">
          <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link @Url.MakeActiveClass("home","index")">
            <i class="nav-icon fas fa-home"></i>
            <p>
              Home
            </p>
          </a>
        </li>

        <!-- Dashboard -->
        <li class="nav-item">
          <a asp-area="" asp-controller="Home" asp-action="Dashboard" class="nav-link @Url.MakeActiveClass("home","dashboard")">
            <i class="nav-icon fas fa-dashboard"></i>
            <p>
              Dashboard
            </p>
          </a>
        </li>

        <!-- Category -->
        <li class="nav-item @Url.MakeMenuOpenClass("Category")">
          <a id="manage" class="nav-link has-treeview @Url.MakeActiveClass("category","_any_")" title="Category" href="#">
            <i class="nav-icon fas fa-th"></i>
            <p>Demo Category</p>
            <i class="fas fa-angle-left right"></i>
          </a>
          <ul class="nav nav-treeview">
            <!-- Page One -->
            <li class="nav-item">
              <a asp-area="" asp-controller="Category" asp-action="PageOne" class="nav-link @Url.MakeActiveClass("category","pageone")">
                <i class="far fa-circle nav-icon"></i>
                <p>Page One</p>
              </a>
            </li>
            
            <!-- Page Two -->
            <li class="nav-item">
              <a asp-area="" asp-controller="Category" asp-action="PageTwo" class="nav-link @Url.MakeActiveClass("category","pagetwo")"> 
                <i class="nav-icon fas fa-th"></i>
                <p>Page Two</p>
              </a>
            </li>
          </ul>
        </li>

        <!-- Forms -->
        <li class="nav-item">
          <a asp-area="" asp-controller="Forms" asp-action="Index" class="nav-link @Url.MakeActiveClass("forms", "index")">
            <i class="nav-icon fas fa-pen"></i>
            <p>
              Forms
            </p>
          </a>
        </li>

        <!-- Test Page -->
        <li class="nav-item">
          <a asp-area="" asp-controller="Forms" asp-action="TestPage" class="nav-link @Url.MakeActiveClass("forms", "testpage")">
            <i class="nav-icon fas fa-biohazard"></i>
            <p>
              Test Page
            </p>
          </a>
        </li>
      </ul>
    </nav> <!-- /.sidebar-menu -->
  </div> <!-- /.sidebar -->
</aside>

Views/Shared/AdminLTE/_Scripts.cshtml
<!-- jQuery 4.5.1 -->
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
<script>
  $.widget.bridge("uibutton", $.ui.button);
</script>

<script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
<script src="~/plugins/chart.js/Chart.bundle.min.js"></script>
<script src="~/plugins/gauge/dist/gauge.js"></script>
<script src="~/plugins/moment/moment.min.js"></script>
<script src="~/plugins/daterangepicker/daterangepicker.js"></script>
<script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<script src="~/plugins/summernote/summernote-bs4.min.js"></script>
<script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<script src="~/js/adminlte.js"></script>


<!-- Validation Scripts -->
<environment include="Development">
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"
            asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator"
            crossorigin="anonymous"
            integrity="sha384-rZfj/ogBloos6wzLGpPkkOr/gpkBNLZ6b6yLy4o+ok+t/SAKlL5mvXLr0OXNi1Hp">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"
            asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive"
            crossorigin="anonymous"
            integrity="sha384-R3vNCHsZ+A2Lo3d5A6XNP7fdQkeswQWTIPfiYwSpEP3YV079R+93YzTeZRah7f/F">
    </script>
</environment>

Views/Shared/AdminLTE/_Styles.cshtml
<!-- Fonts -->
@*<link rel="stylesheet" href="~/fonts/ionicons/ionicons.css" />*@
<link rel="stylesheet" href="~/fonts/fontawesome/css/all.css">

<!-- Bootstrap/jQuery -->
<link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" />
<link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css" />
<link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css" />

<!-- AdminLTE -->
<link rel="stylesheet" href="~/css/adminlte.min.css">

<!-- Other -->
<link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css" />
<link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css" />
<link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.min.css" />
<link rel="stylesheet" href="~/plugins/chart.js/Chart.min.css" />

<link rel="stylesheet" href="~/css/site.css" />

<style type="text/css">
  /* Chart.js */
  @@keyframes chartjs-render-animation {
    from {
      opacity: 0.99;
    }
    to {
      opacity: 1;
    }
  }
  .chartjs-render-monitor {
    animation: chartjs-render-animation 1ms;
  }
  .chartjs-size-monitor,
  .chartjs-size-monitor-expand,
  .chartjs-size-monitor-shrink {
    position: absolute;
    direction: ltr;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    overflow: hidden;
    pointer-events: none;
    visibility: hidden;
    z-index: -1;
  }
  .chartjs-size-monitor-expand > div {
    position: absolute;
    width: 1000000px;
    height: 1000000px;
    left: 0;
    top: 0;
  }
  .chartjs-size-monitor-shrink > div {
    position: absolute;
    width: 200%;
    height: 200%;
    left: 0;
    top: 0;
  }
</style>

Views/Shared/AdminLTE/_TopNavigation.cshtml
@using AdminLTE_MVC.Helpers;  

<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
       <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a asp-area="" asp-controller="Contact" asp-action="Index" class="nav-link">Contact Us</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Message Dropdown Menu -->
      @if(User.Identity.IsAuthenticated)
      {
          <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
              <i class="far fa-comments"></i>
              <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
              <a href="#" class="dropdown-item">
                <!-- Message Start -->
                <div class="media">
                  <img src="~/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                  <div class="media-body">
                    <h3 class="dropdown-item-title">
                      Brad Diesel
                      <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                    </h3>
                    <p class="text-sm">Call me whenever you can...</p>
                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                  </div>
                </div>
                <!-- Message End -->
              </a>
              <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item">
                <!-- Message Start -->
                <div class="media">
                  <img src="~/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                  <div class="media-body">
                    <h3 class="dropdown-item-title">
                      John Pierce
                      <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                    </h3>
                    <p class="text-sm">I got your message bro</p>
                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                  </div>
                </div>
                <!-- Message End -->
              </a>
              <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item">
                <!-- Message Start -->
                <div class="media">
                  <img src="~/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                  <div class="media-body">
                    <h3 class="dropdown-item-title">
                      Nora Silvester
                      <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                    </h3>
                    <p class="text-sm">The subject goes here</p>
                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                  </div>
                </div>
                <!-- Message End -->
              </a>
              <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
          </li>
      }
      <!-- Notifications Dropdown Menu -->
      @if (User.Identity.IsAuthenticated)
      {
          <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
              <i class="far fa-bell"></i>
              <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
              <span class="dropdown-header">15 Notifications</span>
              <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item">
                <i class="fas fa-envelope mr-2"></i> 4 new messages
                <span class="float-right text-muted text-sm">3 mins</span>
              </a>
              <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item">
                <i class="fas fa-users mr-2"></i> 8 friend requests
                <span class="float-right text-muted text-sm">12 hours</span>
              </a>
              <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item">
                <i class="fas fa-file mr-2"></i> 3 new reports
                <span class="float-right text-muted text-sm">2 days</span>
              </a>
              <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
          </li>
      }
      
      <!-- Profile -->
      @if (User.Identity.IsAuthenticated)
      {
          <!-- Dropdown Link -->
          <li class="nav-item dropdown">
            <a class="nav-link btn btn-link text-dark" data-toggle="dropdown" href="#">
              <i class="far fa-user"></i>
            </a>

            <!-- Dropdown Items -->
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
              
              <span class="dropdown-header">@User.Identity.Name</span>
              <div class="dropdown-divider"></div>

              <!-- Profile -->
              <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/Index">
                <i class="fas fa-wrench mr-2"></i>Manage Your Account
              </a>
              <div class="dropdown-divider"></div>

              <!-- Logout -->
              <form class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                <button type="submit" class="nav-link btn btn-link btn-block text-dark">Logout</button>
              </form>
            </div>            
          </li>
      }

      <!-- Fullscreen -->
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->